import = ["~/.config/alacritty/colors/catppuccin-macchiato.toml",]
[font]
normal = { family = "Comic Mono", style = "Normal"}
italic = { family = "Menlo"}
# italic = { family = "Times"}
offset = { x = 1, y = 0}
size = 14
